### ISSUE TITLE
Precision Lost in Float Parsing

### ISSUE THREAD

**Issue by IamfromSpace** [MichaelRFairhurst/wake-compiler#105]
Floats when parsed seem to be losing significance.

ex:

    Num = 1723917869422.8321173;
    Printer.printLine(Num);  //output:  1723920000000
    //6 digits of significance```

However, a machine epsilon check:

    Num = 0.5;
    while ((1 + Num) != 1) {
        Num /= 2;
    }
    Printer.printLine(Num);  //output:  1.1102230246251565e-16
    //Full float64 significance

**Comment by IamfromSpace** [comment]
Looking through the code, I think the issue has to do with storing node data as a (float) instead of a (double).  Number is a (float) in a number of places within the code.

    typedef struct Node {
    	int line;
    	int col;
    	YYLTYPE loc;
    	int node_type;
    	int subnodes;
    	union {
    		char* string;
    		float number;					// number declared as float, not double
    		struct Node** nodes;
    		struct Type* type;
    		struct TypeArray* typearray;
    	} node_data;
    } Node;

**Comment by MichaelRFairhurst** [comment]
Awesome catch! Will merge your PR
