### ISSUE TITLE
Int type

### ISSUE THREAD

**Issue by MichaelRFairhurst** [MichaelRFairhurst/wake-compiler#71]
Need to support proper integers. Need to be careful of js semantics here...int / int should result in a float by default even though the c/cpp backends will likely be weird

**Comment by IamfromSpace** [comment]
###### Overview

Some thoughts/questions on how Ints will interact.  Ideally, Ints are used for special cases only, but one glaring exception is array access.  Wake will have runtime errors if it can't catch possible instances of myArray[.5] at compile time.

Also, floating point numbers in Wake are just called Numbers.  They really need to feel like the bulk of numerical interaction if they are going to deserve the title.

That said, we need to make sure results are intuitive when moving back and forth from Nums and Ints.  People may find themselves writing myArray[(cast Int) myIndex] more often than they'd like.

Should anything without a decimal point be returned as Int if possible and asked?  This is expensive/not good at runtime, but we can tell if a literal could be one or the other without a loss of precision at compile time.  Although, a defined wake size for Ints may be required.  At runtime does any operation involving a Num automatically return a Num or does it return an error?

Should wake mandate an int size to allow for more intuitive parsing?  It might be worthwhile to do 32 bit ints as the standard, and then assume that arbitrary int libraries will handle all other cases.  JS using 32 bit ints (when binary operators are used) may have forced our hand here.  It's (practically) inevitable that not all Nums can be represented as Ints, but as long as as the mantissa of a float is > than the size of an Int, all Ints can be represented as Nums.  This does beg the question of what to do when a language only supports single float--which would break this.

Also, how is overflow handled?  In languages with true int support, overflow will typically wrap around.  In a language like JS where only floats are supported, they will instead keep counting, leading to different outcomes.  Is this an issue?  Checks could be implemented for each Int operation, but this will limit performance.

@MichaelRFairhurst mentioned a special operator for integer division which I think is an excellent idea for creating a simple solution to something that's fairly unintuitive in other languages.  The question is which operator to use.  Mathematics doesn't use integer division often, so the convention is fairly weak, but '\' is used, which makes some intuitive sense.

###### Summary:
 * Should Wake have a standard Int size?  If so what size?
 * Does consistent overflow need to be enforced between platforms?
 * Does wake have standard Float size? When compiling to a language where: `sizeof(Int) > sizeof(Float manissa) == true; $Int = (cast Int) ((cast Num) Int); Int != $Int == true  //in some cases`
 * Does any mathematical operation involving a float automatically return a float, or
 * Should the compiler return an int when asked and able, even if the operation involved floats?
    * cases like 1.0 + 1.0 are easy, but .333_ + .333_ + .333_, not so much, epsilon may need to be used in similar cases, is that worth it?
    * I don't think I like this at runtime, but compile time on literals could work.
      * is it annoy that literals and variables would have inconsistent behavior?

###### Conclusion:

TBD.

**Comment by MichaelRFairhurst** [comment]
overflow in c/c++ is undefined behavior, technically, so that they can optimize

    void myfunc(unsigned int myint) {
        myint += 5;
        if(mint < 5) {
             // this condition will be removed by the optimizer, screwing up overflow conditions
        }
    }

I kinda hate that, but it will be hard to work around, so maybe we can embrace that for all sorts of reasons.

I wish we could just settle on 64 bit ints...I think I'd rather emulate 64 bit behavior in a 32 bit environment than emulate 32 in a 64. Is that backwards of me? will have to think about it....

**Comment by MichaelRFairhurst** [comment]
On casts, I'd expect Num to have

    Num.toInt(); // throws if not a whole number
    Num.toIntSafe(); // returns a Num?, nothing if not a whole number

making it

    return myArray[myNum.toInt()];

which at least is a bit nicer than casts.

Its common that `1` is an int, and `1.0` or even `1.` are used where a float is desired. We should stick with this.

I'm not too concerned about mathematical operations returning Nums instead of Ints. It will work pretty nicely with

    Num * Num = Num
    Num * Int = Num
    Int * Num = Num
    Int * Int = Int
    Num.toThe(Num) = Num
    Int.toThe(Int) = Int
    Int.toThe(Num) = Num
    Num.toThe(Int) = Num
    Int / Int = Num
    Num /  Num = Num

Only really things like sqrt(4) returning a Num will be that annoying. Most mathematical ops that aren't basic arithmetic rarely return whole numbers.

**Comment by MichaelRFairhurst** [comment]
Been working on this!

Found a few edge cases:

     Num << Num; // error! Cannot bitshift by a noninteger
     Num | Int; // decided to make this just err out rather than perform an implicit cast

     Int += Num; // error! Even though Int + Num is OK
     Int /= Int; // error! Use \= instead (once if exists)

I think I have a good number of tests, not all are passing yet but its enough I've moved to refactoring my existing code to use it

**Comment by MichaelRFairhurst** [comment]
This is done!
