### ISSUE TITLE
Bugs in Mathematical Parsing

### ISSUE THREAD

**Issue by IamfromSpace** [MichaelRFairhurst/wake-compiler#97]
* Expression {a*-b} throws an error at compile time:
 * b should be negated, then the multiplication evaluated.
 * This does not throw an error when b is a hardcode value, ex {a*-5}

________________

* Expression {sin(.5)} throws an error at compile time:
 * ".5" should be interpreted as "0.5"

**Comment by MichaelRFairhurst** [comment]
Will work with you to get you the bugfix without having to cut a whole release!

**Comment by IamfromSpace** [comment]
Not a huge deal, easy to work around when you know what it is.  Just a change you'll want to make in a future release.
